
INSERT INTO COMPANY (ID, NM_NAME) VALUES (1, 'CAST');

INSERT INTO PROJECT (ID, NM_NAME, ID_COMPANY) VALUES (1, 'SAJ', 1);

INSERT INTO SITUATION (ID, NM_NAME, CD_CODE) VALUES (1, 'OPENED', 1);
INSERT INTO SITUATION (ID, NM_NAME, CD_CODE) VALUES (2, 'STARTED', 2);
INSERT INTO SITUATION (ID, NM_NAME, CD_CODE) VALUES (3, 'VALIDATING', 3);
INSERT INTO SITUATION (ID, NM_NAME, CD_CODE) VALUES (4, 'FINISHED', 4);